# Generated by Django 5.0.1 on 2024-02-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0006_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
