# Generated by Django 5.0.1 on 2024-02-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0008_blog_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='likes',
        ),
    ]
